apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .values.service.nodePort }}
      {{- end }}

